# Form implementation generated from reading ui file 'ui/app.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 239)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckSuppr = QtWidgets.QCheckBox(self.groupBox)
        self.ckSuppr.setObjectName("ckSuppr")
        self.gridLayout_2.addWidget(self.ckSuppr, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineFile.setReadOnly(True)
        self.lineFile.setObjectName("lineFile")
        self.horizontalLayout_2.addWidget(self.lineFile)
        self.btnOpenFile = QtWidgets.QToolButton(self.centralwidget)
        self.btnOpenFile.setText("")
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btnOpenFile.setIcon(icon)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout_2.addWidget(self.btnOpenFile)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineDest = QtWidgets.QLineEdit(self.centralwidget)
        self.lineDest.setReadOnly(True)
        self.lineDest.setObjectName("lineDest")
        self.horizontalLayout.addWidget(self.lineDest)
        self.btnOpenDest = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btnOpenDest.setIcon(icon)
        self.btnOpenDest.setObjectName("btnOpenDest")
        self.horizontalLayout.addWidget(self.btnOpenDest)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.btnExtract = QtWidgets.QPushButton(self.centralwidget)
        self.btnExtract.setObjectName("btnExtract")
        self.gridLayout.addWidget(self.btnExtract, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UnityPackageExtractor"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.ckSuppr.setText(_translate("MainWindow", "Supprimer le fichier à la fin de l\'extraction"))
        self.lineFile.setPlaceholderText(_translate("MainWindow", "Choisir le fichier à extraire"))
        self.lineDest.setPlaceholderText(_translate("MainWindow", "Choisir le repertoire de destination"))
        self.btnOpenDest.setText(_translate("MainWindow", "..."))
        self.btnExtract.setText(_translate("MainWindow", "Extraire"))
