# Form implementation generated from reading ui file '.\ui\app.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(559, 256)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ckSuppr = QtWidgets.QCheckBox(parent=self.groupBox)
        self.ckSuppr.setObjectName("ckSuppr")
        self.gridLayout_2.addWidget(self.ckSuppr, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.filesNames = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.filesNames.setReadOnly(True)
        self.filesNames.setObjectName("filesNames")
        self.horizontalLayout_2.addWidget(self.filesNames)
        self.btnOpenFile = QtWidgets.QToolButton(parent=self.centralwidget)
        self.btnOpenFile.setText("")
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btnOpenFile.setIcon(icon)
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.horizontalLayout_2.addWidget(self.btnOpenFile)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineDest = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineDest.setReadOnly(True)
        self.lineDest.setObjectName("lineDest")
        self.horizontalLayout.addWidget(self.lineDest)
        self.btnOpenDest = QtWidgets.QToolButton(parent=self.centralwidget)
        icon = QtGui.QIcon.fromTheme("document-open")
        self.btnOpenDest.setIcon(icon)
        self.btnOpenDest.setObjectName("btnOpenDest")
        self.horizontalLayout.addWidget(self.btnOpenDest)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.btnExtract = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExtract.setObjectName("btnExtract")
        self.gridLayout.addWidget(self.btnExtract, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 559, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UnityPackageExtractor"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.ckSuppr.setText(_translate("MainWindow", "Supprimer le fichier ├á la fin de l\'extraction"))
        self.filesNames.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Choisir les fichier a extraire</p></body></html>"))
        self.lineDest.setPlaceholderText(_translate("MainWindow", "Choisir le repertoire de destination"))
        self.btnOpenDest.setText(_translate("MainWindow", "..."))
        self.btnExtract.setText(_translate("MainWindow", "Extraire"))
